### ISSUE TITLE
Optimus +eGPU

### ISSUE THREAD

**Issue by hcal** [xulongwu4/solus-nvidia-optimus-manager#1]
Would it be possible to support a Thunderbolt eGPU in addition to the internal intel and nvidia GPUs?  The use case being, I switch between the two internal GPUs as needed why on the road and use the thunderbolt dock with a monitor plugged in to the dock when at home.

**Comment by xulongwu4** [comment]
This is currently not supported. It will at least depend on the kernel support of eGPU devices.
