### ISSUE TITLE
Package this repository for Solus

### ISSUE THREAD

**Issue by JeffLabonte** [xulongwu4/solus-nvidia-optimus-manager#10]
Hey there! 

I would like to know if you would like to have this script to Solus. I would like to package it! But I wanted to have your opinion before I ask the Solus developper to add this repository to Solus!

Thank you! Thank you for this solution!

**Comment by xulongwu4** [comment]
@JeffLabonte Thanks for your interest in this project. There is actually a request for this package in the Solus dev tracker: https://dev.getsol.us/T8579. I also posted my opinion there. I hope I will at least have the time to test the script (and have installation method) for the other supported desktop environment before it get included in the official repo.

**Comment by JeffLabonte** [comment]
I will close this "issue" then since it is in discussion with the developers of Solus. I hope, this project will be integrated to the main repository someday :)
